version: '2'
services:
  dev:
    image: "mpy-esp32:v1.18_4.0.2"
    build:
      context: "./mpy-esp32"
      dockerfile: "Dockerfile"
      args:
        # Update 'MPY_TAG' to pick an micropython tag: master, v1.18, v1.17
        MPY_TAG: "v1.18"
        # Update 'IDF_TAG' to pick an espressif/idf tag: v4.0.2, v4.1.1, v4.2, v4.4, v4.3.1
        # See also: ports/esp32/README.md - https://github.com/micropython/micropython/blob/master/ports/esp32/README.md
        #   ...
        #   You can replace `v4.0.2` with `v4.1.1` or `v4.2` or any other supported version.
        #   (You don't need a full recursive clone; see the ci_esp32_setup function
        #    in tools/ci.sh in this repository for more detailed set-up commands.)
        #   ...
        #   Note: If you are building MicroPython for the ESP32-S2, ESP32-C3 or ESP32-S3,
        #         please ensure you are using the following required IDF versions:
        #         - ESP32-S3 currently requires latest master, but eventually `v4.4` or later when it's available.
        #         - ESP32-S2 and ESP32-C3 require `v4.3.1` or later. 
        #   ...
        IDF_TAG: "v4.0.2"
    volumes:
      - ..:/home/vscode/ws:cached
    tty: true