version: '2'
services:
  dev:
    image: "mpy-esp32:v1.18"
    build:
      context: "./mpy-esp32"
      dockerfile: "Dockerfile"
      args:
        # Using pair 'MPY_TAG'/'IDF_TAG', v1.18/v4.2.2
        # Update 'MPY_TAG' to pick an micropython tag: master, v1.18, v1.17
        MPY_TAG: "v1.18"
        # Update 'IDF_TAG' to pick an espressif/idf tag: latest, release-v4.3, v4.2.2
        IDF_TAG: "v4.2.2"
    volumes:
      - ..:/home/vscode/ws:cached
    tty: true